"""Submódulo de contratos de datos formales."""
from .models import (
    SessionMetadata,
    ParticipantInfo,
    AudioFileInfo,
    SessionTranscript,
    Utterance,
    UserProfile,
    TraitEvaluation,
    EvidenceQuote,
    BigFiveTraits,
    CommunicationStyle,
    GroupRole,
    DialectMarkers,
    InterlocutorAffinity,
    SocialDynamics,
    GroupLore,
    EmotionalTriggers,
    ActivityInitiative,
    TemporalPatterns,
)

__all__ = [
    "SessionMetadata",
    "ParticipantInfo",
    "AudioFileInfo",
    "SessionTranscript",
    "Utterance",
    "UserProfile",
    "TraitEvaluation",
    "EvidenceQuote",
    "BigFiveTraits",
    "CommunicationStyle",
    "GroupRole",
    "DialectMarkers",
    "InterlocutorAffinity",
    "SocialDynamics",
    "GroupLore",
    "EmotionalTriggers",
    "ActivityInitiative",
    "TemporalPatterns",
]
